"""Complete synthetic rows with safe, fixed source lineage for unit tests."""

from __future__ import annotations

from collections.abc import Mapping
from datetime import date
from pathlib import PurePosixPath
from typing import Literal

from finproof.domain.source import SourceCell, SourceRow

SNAPSHOT_DATE = date(2026, 8, 24)

BOND_COLUMNS = (
    "PD_NO",
    "PD_EXG_MKT",
    "PD_NM",
    "PD_ABRV_NM",
    "PD_ENG_NM",
    "PD_ABRV_ENG_NM",
    "PD_CTRY_CD",
    "PD_PBCM",
    "STD_PD_MCLS_NM",
    "STD_PD_SCLS_NM",
    "BD_KND",
    "CURR_CD",
    "ISU_BAL_AMT",
    "ISU_DT",
    "MAT_DT",
    "SRFC_IRT",
    "PD_EVCO_CRD_GRD",
    "PD_RISK_GCD",
    "PD_STD_INFO_UPDATE",
    "BUY_YIELD",
    "CORP_PRETAX_YIELD",
    "CORP_AFTER_TAX_YIELD",
    "AFTER_TAX_YIELD",
    "PREF_TAX_YIELD",
    "AVG_ANNUAL_TAX_YIELD",
    "DEPO_EQUIV_YIELD_154",
    "BUYABLE_QUANTITY",
    "REMAINING_DAYS",
    "DUR",
    "COV",
    "NDY_DUR",
    "NDY_COV",
    "EVAL_PRICE",
    "APPLIED_YIELD",
    "DIRTY",
    "NDY_EVAL_PRICE",
    "NDY_APPLIED_YIELD",
    "NDY_DIRTY",
    "CRD_GRD",
    "CRD_GRD_DT",
)

REFRESHED_BOND_COLUMNS = (
    "after_tax_yield",
    "applied_yield",
    "avg_annual_tax_yield",
    "bdbns_abl_chnl_nm",
    "bdbns_abl_chnl_tcd",
    "bd_inrt_tcd",
    "bd_intp_tcd",
    "bd_knd",
    "bd_ofr_tcd",
    "bd_tisu_a",
    "buyable_quantity",
    "buy_yield",
    "corp_after_tax_yield",
    "corp_pretax_yield",
    "cov",
    "crd_grd",
    "crd_grd_dt",
    "curr_cd",
    "depo_equiv_yield_154",
    "depo_equiv_yield_495",
    "dirty",
    "dur",
    "eval_price",
    "exg_close_price",
    "exg_close_price_base_dt",
    "exg_close_yield",
    "exrt_grte_ern_r",
    "exrt_grte_ern_r_tcd",
    "exrt_rpy_r",
    "info_base_dt",
    "info_seq",
    "isu_bal_amt",
    "isu_dt",
    "mat_dt",
    "ndy_applied_yield",
    "ndy_cov",
    "ndy_dirty",
    "ndy_dur",
    "ndy_eval_price",
    "pd_abrv_eng_nm",
    "pd_abrv_nm",
    "pd_ctry_cd",
    "pd_eng_nm",
    "pd_exg_mkt",
    "pd_nm",
    "pd_no",
    "pd_pbcm",
    "pd_pen_tr_yn",
    "pd_risk_gcd",
    "pd_risk_nm",
    "pd_std_info_update",
    "pref_tax_yield",
    "remaining_days",
    "sale_yield_base_dt",
    "srfc_irt",
    "std_pd_mcls_nm",
    "std_pd_scls_nm",
    "trade_price",
)

DOMESTIC_LISTED_COLUMNS = (
    "cu_base_index",
    "cu_charge_etc_rt",
    "cu_charge_rt",
    "cu_fund_mgmt_co",
    "cu_lev_fector",
    "cu_strtegy",
    "cu_upt_dt",
    "du_bpr",
    "du_chas_errt",
    "du_chas_errt_base_dt",
    "du_clpr",
    "du_diff_rt",
    "du_diff_rt_base_dt",
    "du_er_1d",
    "du_er_1m",
    "du_er_1y",
    "du_er_3m",
    "du_er_6m",
    "du_er_ytd",
    "du_hpr",
    "du_last_aum",
    "du_last_nav",
    "du_lpr",
    "du_nav_base_dt",
    "du_nav_rnf_amt",
    "du_nav_yday",
    "du_upt_dt",
    "du_val_1d",
    "du_val_1m",
    "du_val_5d",
    "du_vlty_1m",
    "du_vlty_1y",
    "du_vlty_3m",
    "du_vlty_6m",
    "du_vlty_base_dt",
    "du_vol_1d",
    "du_vol_avg_1m",
    "du_vol_avg_5d",
    "fn_average_coupon",
    "fn_average_maturity",
    "fn_average_quality",
    "fn_base_dt",
    "fn_effective_duration",
    "fn_effective_maturity",
    "fn_modified_duration",
    "fn_nominal_maturity",
    "fn_portfolio_dt",
    "pd_abrv_nm",
    "pd_circ_net_tamt",
    "pd_circ_stk_cnt",
    "pd_curr_cd",
    "pd_curr_nm",
    "pd_divd_amt_ann",
    "pd_divd_amt_pshr",
    "pd_dvid_base_dt",
    "pd_dvid_cycl",
    "pd_dvid_inc_dist",
    "pd_dvid_nav",
    "pd_dvid_pay_cnt",
    "pd_dvid_pay_months",
    "pd_dvid_prc_base_dt",
    "pd_dvid_tax_basis",
    "pd_dvid_yield",
    "pd_exg_mkt_cd",
    "pd_exg_mkt_nm",
    "pd_grp_no",
    "pd_isin_cd",
    "pd_itm_no",
    "pd_itm_no_ma",
    "pd_lst_stk_cnt",
    "pd_lste_dt",
    "pd_lstg_dt",
    "pd_mkt_id",
    "pd_mkt_nm",
    "pd_net_tamt",
    "pd_nm",
    "pd_pen_risk_nm",
    "pd_pen_tr_yn",
    "pd_ric",
    "pd_risk_cd",
    "pd_risk_nm",
    "pd_sale_yn",
    "pd_sect_cd",
    "pd_spac_yn",
    "pd_stk_cnt",
    "pd_ticker",
    "pd_tr_yn",
    "ref_ast_type",
    "ref_base_dt",
    "ref_base_index",
    "ref_fund_mgmt_co",
    "ref_geo_focus",
    "ru_mkt_price",
    "ru_mkt_volume",
    "wu_core_yn",
    "wu_inv_ast_type",
    "wu_inv_rgn",
    "wu_upt_dt",
)

OVERSEAS_LISTED_COLUMNS = (
    "cu_base_index",
    "cu_charge_rt",
    "cu_etn_yn",
    "cu_fund_mgmt_co",
    "cu_index_repl_mthd",
    "cu_index_tracking_yn",
    "cu_inverse_short_yn",
    "cu_lev_fector",
    "cu_strtegy",
    "cu_upt_dt",
    "du_base_dt_match_yn",
    "du_bpr",
    "du_clpr",
    "du_clpr_base_dt",
    "du_clpr_src",
    "du_diff_rt",
    "du_er_1d",
    "du_hpr",
    "du_last_aum",
    "du_last_nav",
    "du_lpr",
    "du_nav_base_dt",
    "du_opr",
    "du_upt_dt",
    "du_val_1d",
    "du_vol_1d",
    "pd_abrv_nm",
    "pd_curr_cd",
    "pd_exg_mkt_cd",
    "pd_grp_no",
    "pd_isin_cd",
    "pd_itm_no",
    "pd_itm_no_ma",
    "pd_lipper_id",
    "pd_lstg_dt",
    "pd_lst_price",
    "pd_lst_stk_cnt",
    "pd_mkt_id",
    "pd_nm",
    "pd_sale_yn",
    "pd_trd_ccy",
    "pd_tr_yn",
    "pd_us_cik",
    "ru_mkt_price",
    "ru_mkt_volume",
    "wu_core_yn",
    "wu_inv_ast_type",
    "wu_inv_rgn",
    "wu_upt_dt",
)

PUBLIC_FUND_COLUMNS = (
    "bmrk_eng_nm",
    "bmrk_nm",
    "curr_cd",
    "exchdg_yn",
    "fd_estb_ctry_cd",
    "fd_ivst_rgn_desc",
    "fd_mm18_ern_r",
    "fd_mm1_ern_r",
    "fd_mm3_ern_r",
    "fd_mm6_ern_r",
    "fd_nast_suma",
    "fd_set_pcd",
    "fd_wk1_ern_r",
    "fd_yr1_ern_r",
    "fd_yr2_ern_r",
    "fd_yr3_ern_r",
    "fd_yr5_ern_r",
    "frc_bpr_itm_yn",
    "fss_itm_no",
    "hdge_fd_yn",
    "int_dvd_desc",
    "itm_abrv_nm",
    "itm_eabrv_nm",
    "itm_eng_nm",
    "itm_nm",
    "itm_no",
    "kofia_fd_ccd",
    "ksd_itm_no",
    "mtco_itm_no",
    "ofsfd_yn",
    "or_attr_desc",
    "or_co_xtn_itt_cd",
    "ovrs_fd_desc",
    "pers_corp_desc",
    "pfiv_sale_cntl_tcd",
    "prfd_attr_cd",
    "prvo_fd_desc",
    "prvo_pbff_desc",
    "rptt_ksd_itm_no",
    "sale_yn",
    "std_itm_no",
    "thco_sale_yn",
    "trusc_xtn_itt_cd",
    "zrin_fd_ivst_risk_gcd",
    "zrin_fd_ivst_risk_grd_nm",
)

OVERSEAS_DEFAULTS = {
    "pd_itm_no": "BND.O",
    "pd_itm_no_ma": "BND.O",
    "pd_abrv_nm": "BND",
    "pd_grp_no": "ETF",
    "pd_nm": "Test Overseas ETF",
    "pd_trd_ccy": "USD",
    "pd_lstg_dt": "20070403",
    "cu_charge_rt": "0.020000",
    "du_last_aum": "157396600000.00",
    "du_er_1d": "0.000000",
    "cu_upt_dt": "20260614",
    "du_clpr_base_dt": "20260616",
    "du_nav_base_dt": "20260822",
    "du_upt_dt": "20260616",
    "wu_upt_dt": "20260614",
}

PUBLIC_FUND_DEFAULTS = {
    "itm_no": "KR5114601001",
    "prfd_attr_cd": "C101",
    "itm_nm": "테스트 공모펀드",
    "itm_abrv_nm": "테스트펀드",
    "curr_cd": "KRW",
    "fd_nast_suma": "1000000.0000",
    "or_attr_desc": "주식형",
    "sale_yn": "판매중",
    "thco_sale_yn": "Y",
    "ksd_itm_no": "KR5114601001",
}

TableId = Literal["PRBD01N001", "PREF01N001", "PREF02N001", "PRFD01N001"]


def _excel_column_letter(number: int) -> str:
    letters: list[str] = []
    remaining = number
    while remaining:
        remaining, remainder = divmod(remaining - 1, 26)
        letters.append(chr(ord("A") + remainder))
    return "".join(reversed(letters))


def source_row(
    table_id: TableId,
    values: Mapping[str, str] | None = None,
    *,
    excel_row: int = 2,
    applicable_dates: Mapping[str, date | None] | None = None,
) -> SourceRow:
    """Return a complete source row with only safe, fixed fixture lineage."""
    columns: tuple[str, ...]
    defaults: Mapping[str, str]
    if table_id == "PRBD01N001":
        refreshed = bool(values and set(values) & set(REFRESHED_BOND_COLUMNS))
        columns = REFRESHED_BOND_COLUMNS if refreshed else BOND_COLUMNS
        defaults = (
            {
                "pd_no": "KR0000000001",
                "pd_exg_mkt": "장내",
                "info_base_dt": "20260822",
                "info_seq": "1",
                "pd_nm": "테스트 채권",
                "pd_abrv_nm": "채권",
                "curr_cd": "KRW",
                "bd_knd": "회사채",
                "isu_dt": "20200101",
                "mat_dt": "20270711",
                "buyable_quantity": "1",
                "remaining_days": "365",
            }
            if refreshed
            else {
                "PD_NO": "KR0000000001",
                "PD_NM": "테스트 채권",
                "PD_ABRV_NM": "채권",
                "CURR_CD": "KRW",
                "BD_KND": "회사채",
                "ISU_DT": "20200101",
                "MAT_DT": "20270711",
                "BUYABLE_QUANTITY": "1",
                "REMAINING_DAYS": "365",
            }
        )
    elif table_id == "PREF01N001":
        columns = DOMESTIC_LISTED_COLUMNS
        defaults = {
            "pd_itm_no": "KR7000000001",
            "pd_itm_no_ma": "A000001",
            "pd_grp_no": "ETF",
            "pd_nm": "테스트 ETF",
            "pd_abrv_nm": "테스트",
            "pd_curr_cd": "CURR_CD_KRW",
            "pd_sale_yn": "1",
            "pd_tr_yn": "0",
            "pd_lstg_dt": "20200101",
            "pd_lste_dt": "99991231",
            "cu_upt_dt": "20260824",
            "du_upt_dt": "20260821",
            "wu_upt_dt": "20260821",
        }
    elif table_id == "PREF02N001":
        columns = OVERSEAS_LISTED_COLUMNS
        defaults = OVERSEAS_DEFAULTS
    else:
        columns = PUBLIC_FUND_COLUMNS
        defaults = PUBLIC_FUND_DEFAULTS
    supplied = dict(values or {})
    unknown = set(supplied) - set(columns)
    if unknown:
        raise KeyError(f"unknown source columns: {sorted(unknown)}")
    dates = dict(applicable_dates or {})
    unknown_dates = set(dates) - set(columns)
    if unknown_dates:
        raise KeyError(f"unknown applicable-date columns: {sorted(unknown_dates)}")
    raw = dict.fromkeys(columns, "") | defaults | supplied
    cells = tuple(
        SourceCell(
            column_name=column,
            excel_column_number=number,
            excel_column_letter=_excel_column_letter(number),
            raw_value=raw[column],
            applicable_date=dates.get(column),
        )
        for number, column in enumerate(columns, start=1)
    )
    return SourceRow(
        source_table=table_id,
        source_file=PurePosixPath(f"data/{table_id}_fixture.xlsx"),
        source_sheet="data",
        source_row_number=excel_row,
        source_checksum="a" * 64,
        source_snapshot_date=SNAPSHOT_DATE,
        raw_payload=tuple(cell.raw_value for cell in cells),
        cells=cells,
    )
